### PR TITLE
Expand Create Controller command to support multiple methods

### PR DESCRIPTION
**Pull request by garretthyder**
This little patch takes advantage of the existing '@' delimiter to allow multiple methods to be created through the create controller command.

Example Usage;
`php ayuco create controller:ControllerName@FirstMethod@SecondMethod@etcMethod`
This call would create the ControllerName.php file and inject 3 method calls for the additional items added after the '@' delimiter

### CODE REVIEW

**Comment by garretthyder** [comment]
@amostajo also note the docs don't currently method that the Create Controller Command supports adding a function name after the '@' so even if this isn't accepted would be good to disclose that in the docs as I only found it by diving into the code.

**Comment by amostajo** [comment]
@garretthyder 
https://www.wordpress-mvc.com/v1/controllers/#ayuco

**Comment by garretthyder** [comment]
O nice that's a much more expanded view. I was looking at The Basics > Commands;
https://www.wordpress-mvc.com/v1/ayuco/

What are your thoughts on the multi-method creation chaining I setup in this PR. If not useful for the tool no worries I can always add additional methods manually

**Review by amostajo — APPROVED** [review]

**Comment by amostajo** [comment]
@garretthyder Any cool idea is always welcome!

Add a new PR to review it!

**Pull request merged**
